# Generated by Django 2.0.9 on 2020-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability',
            },
        ),
    ]
